language: python
sudo: required
group: deprecated-2017Q4
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
    - PYTEST_AGRS="--ignore src/openprocurement.archivarius.core/openprocurement/archivarius/core/tests/bridge.py"
  matrix:
    - MODULE=openprocurement.api
    - MODULE=openprocurement.archivarius.plans
    - MODULE=openprocurement.contracting.api
    - MODULE=openprocurement.planning.api
    - MODULE=openprocurement.tender.core
    - MODULE=openprocurement.tender.openeu
    - MODULE=openprocurement.archivarius.contracts
    - MODULE=openprocurement.archivarius.tenders
    - MODULE=openprocurement.historical.core
    - MODULE=openprocurement.tender.belowthreshold
    - MODULE=openprocurement.tender.esco
    - MODULE=openprocurement.tender.openua
    - MODULE=openprocurement.archivarius.core
    - MODULE=openprocurement.concord
    - MODULE=openprocurement.historical.tender
    - MODULE=openprocurement.tender.competitivedialogue
    - MODULE=openprocurement.tender.limited
    - MODULE=openprocurement.tender.openuadefense
cache:
  directories:
    - eggs
before_install:
  - sh bootstrap.sh
install:
  - bin/buildout -N -c buildout.cfg.example
script:
  - bin/py.test src/$MODULE/ $PYTEST_AGRS
  - SANDBOX_MODE=True bin/py.test src/$MODULE $PYTEST_AGRS
