language: python
sudo: required
group: deprecated-2017Q4
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
    - PYTEST_AGRS="--ignore src/openprocurement.archivarius.core/openprocurement/archivarius/core/tests/bridge.py"
  matrix:
    - MODULE=openprocurement.api SANDBOX_MODE=True
    - MODULE=openprocurement.api SANDBOX_MODE=False
    - MODULE=openprocurement.archivarius.plans SANDBOX_MODE=True
    - MODULE=openprocurement.archivarius.plans SANDBOX_MODE=False
    - MODULE=openprocurement.contracting.api SANDBOX_MODE=True
    - MODULE=openprocurement.contracting.api SANDBOX_MODE=False
    - MODULE=openprocurement.planning.api SANDBOX_MODE=True
    - MODULE=openprocurement.planning.api SANDBOX_MODE=False
    - MODULE=openprocurement.tender.core SANDBOX_MODE=True
    - MODULE=openprocurement.tender.core SANDBOX_MODE=False
    - MODULE=openprocurement.tender.openeu SANDBOX_MODE=True
    - MODULE=openprocurement.tender.openeu SANDBOX_MODE=False
    - MODULE=openprocurement.archivarius.contracts SANDBOX_MODE=True
    - MODULE=openprocurement.archivarius.contracts SANDBOX_MODE=False
    - MODULE=openprocurement.archivarius.tenders SANDBOX_MODE=True
    - MODULE=openprocurement.archivarius.tenders SANDBOX_MODE=False
    - MODULE=openprocurement.historical.core SANDBOX_MODE=True
    - MODULE=openprocurement.historical.core SANDBOX_MODE=False
    - MODULE=openprocurement.tender.belowthreshold SANDBOX_MODE=True
    - MODULE=openprocurement.tender.belowthreshold SANDBOX_MODE=False
    - MODULE=openprocurement.tender.esco SANDBOX_MODE=True
    - MODULE=openprocurement.tender.esco SANDBOX_MODE=False
    - MODULE=openprocurement.tender.openua SANDBOX_MODE=True
    - MODULE=openprocurement.tender.openua SANDBOX_MODE=False
    - MODULE=openprocurement.archivarius.core SANDBOX_MODE=True
    - MODULE=openprocurement.archivarius.core SANDBOX_MODE=False
    - MODULE=openprocurement.concord SANDBOX_MODE=True
    - MODULE=openprocurement.concord SANDBOX_MODE=False
    - MODULE=openprocurement.historical.tender SANDBOX_MODE=True
    - MODULE=openprocurement.historical.tender SANDBOX_MODE=False
    - MODULE=openprocurement.tender.competitivedialogue SANDBOX_MODE=True
    - MODULE=openprocurement.tender.competitivedialogue SANDBOX_MODE=False
    - MODULE=openprocurement.tender.limited SANDBOX_MODE=True
    - MODULE=openprocurement.tender.limited SANDBOX_MODE=False
    - MODULE=openprocurement.tender.openuadefense SANDBOX_MODE=True
    - MODULE=openprocurement.tender.openuadefense SANDBOX_MODE=False
cache:
  directories:
    - eggs
before_install:
  - sh bootstrap.sh
install:
  - bin/buildout -N -c buildout.cfg.example
script:
  - bin/py.test src/$MODULE/ $PYTEST_AGRS
