language: python
sudo: required
group: deprecated-2017Q4
before_script:
  - sudo apt-get -qq update
python:
  - "2.7"
env:
  matrix:
    - CFG="development.cfg"
    - CFG="sandbox.cfg"
    - CFG="preproduction.cfg"
    - CFG="production.cfg"
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==11.3
  - sh 'sed -i "s/development.cfg/$CFG/g" buildout.cfg'
install:
  - python2 bootstrap.py
script:
  - bin/buildout -N
after_success:
  - bin/coveralls

